<?php
namespace app\home\controller;

use app\common\controller\HomeCom;
use think\Controller;

class Base extends HomeCom
{

    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        if (!$this->is_login()) {
            $this->redirect('home/Login/home_page');
        }
    }
}